version: '3'

services:
  rabbit:
    restart: always
    image: rabbitmq:latest
  web:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
    extra_hosts:
      - sql-host:192.168.1.9
    environment:
      - OPTIMA_SERVER=tcp:sql-host
    env_file:
      - ./.env.prod
    depends_on:
      - db
    command: "/home/app/web/entrypoint.prod.sh"
  db:
      restart: always
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env.prod.db
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: celery -A config worker -l info
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - rabbit
      - web
  beat:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./.env.prod
    depends_on:
      - celery
      - rabbit
      - web
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
