# Generated by Django 3.2.6 on 2022-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211003_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalunit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='optima_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='optima_id',
            field=models.PositiveIntegerField(),
        ),
    ]
