# Generated by Django 3.2.6 on 2022-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220630_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='pkwiu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pkwiu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
