# Generated by Django 3.2.6 on 2022-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumenttype',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
