# Generated by Django 3.2.6 on 2022-06-27 06:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
        ('documents', '0002_auto_20220623_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='numbering',
            field=models.CharField(default=datetime.datetime(2022, 6, 27, 8, 10, 30, 226397), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='type_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumenttype',
            name='numbering',
            field=models.CharField(default=datetime.datetime(2022, 6, 27, 8, 10, 47, 698583), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldocumenttype',
            name='type_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('optima_id', models.PositiveIntegerField(blank=True, null=True)),
                ('optima_full_number', models.CharField(blank=True, max_length=255, null=True)),
                ('value_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('destination_store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stores.store')),
                ('document_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.documenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stores.store')),
            ],
            options={
                'verbose_name': 'historical document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('optima_id', models.PositiveIntegerField(blank=True, null=True)),
                ('optima_full_number', models.CharField(blank=True, max_length=255, null=True)),
                ('value_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_destination', to='stores.store')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
                ('source_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_source', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
