# Generated by Django 3.2.6 on 2022-06-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('documents', '0003_auto_20220627_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_destination', to='stores.store'),
        ),
    ]
