# Generated by Django 3.2.6 on 2022-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20220627_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='value_gross',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='value_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='value_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='value_gross',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='value_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='value_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
