# Generated by Django 3.2.6 on 2022-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20220627_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='exported',
            field=models.BooleanField(default=False),
        ),
    ]
