# Generated by Django 3.2.6 on 2022-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20220628_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
