# Generated by Django 3.2.6 on 2022-06-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20220630_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='gross_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitem',
            name='gross_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitem',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12),
        ),
    ]
