# Generated by Django 3.2.6 on 2022-07-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentgroup_historicaldocumentgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldocumentgroup',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documentgroup',
            name='document_type',
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='document_type',
            field=models.ManyToManyField(to='documents.DocumentType'),
        ),
    ]
