# Generated by Django 3.2.6 on 2022-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20220704_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type_details_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='document_type_details_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
