# Generated by Django 3.2.6 on 2022-07-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20220705_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type_details_id',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='document_type_details_id',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='details_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumenttype',
            name='details_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
