# Generated by Django 3.2.6 on 2022-07-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20220705_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentgroup',
            name='document_type',
            field=models.ManyToManyField(related_name='group', to='documents.DocumentType'),
        ),
    ]
