# Generated by Django 3.2.6 on 2022-07-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_documentgroup_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='documents.documentgroup'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='document_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.documentgroup'),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='document_type',
            field=models.ManyToManyField(related_name='groups', to='documents.DocumentType'),
        ),
    ]
