# Generated by Django 3.2.6 on 2022-09-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_document_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='type',
        ),
    ]
