# Generated by Django 3.2.6 on 2022-09-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='document_creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='document_date',
            field=models.DateTimeField(null=True),
        ),
    ]
