# Generated by Django 3.2.6 on 2022-09-13 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20220912_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 13, 19, 46, 11, 618601)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 13, 19, 46, 17, 314640)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 13, 19, 46, 29, 552476), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 13, 19, 46, 34, 344097), editable=False),
            preserve_default=False,
        ),
    ]
