# Generated by Django 3.2.6 on 2022-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_auto_20220913_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='realized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='realized',
            field=models.BooleanField(default=False),
        ),
    ]
