# Generated by Django 3.2.6 on 2022-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_auto_20220920_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
