# Generated by Django 3.2.6 on 2022-09-01 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_auto_20220707_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimport',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='import',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
